-- Cidades
create table public.cities (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name character varying not null,
  constraint cities_pkey primary key (id)
) TABLESPACE pg_default;

-- Categorias
create table public.categories (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name character varying not null,
  constraint categories_pkey primary key (id)
) TABLESPACE pg_default;

-- Serviços
create table public.services (
  id bigint generated by default as identity not null,
  name character varying not null,
  created_at timestamp with time zone not null default now(),
  city_id bigint null,
  category_id bigint null,
  logo_url text null,
  constraint services_pkey primary key (id),
  constraint services_category_id_fkey foreign KEY (category_id) references categories (id) on update CASCADE on delete set null,
  constraint services_city_id_fkey foreign KEY (city_id) references cities (id) on update CASCADE on delete set null
) TABLESPACE pg_default;